services:
  app:
    build:
      context: .
      target: deps
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run dev
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      PORT: 8080
      DB_URL: mongodb://mongo:27017/OrbitOps
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis
